// Builds the v2 exercise-bank migration from the standalone training tool
// (outil-entrainement-escalade.html): 82 exercises × 3 variants, FR/EN/ES, with pose data.
// Usage: node scripts/build-bank-v2.mjs <path/to/outil-entrainement-escalade.html>
//
// The migration: removes the built-in exercises that v2 replaces (REPLACED in
// src/domain/exercises.js), moves the remaining ones to the v2 categories, and
// upserts the 82 v2 exercises as 'library' (teachers/admins; students via assignment).
import { readFileSync, writeFileSync } from "node:fs";

const file = process.argv[2];
if (!file) throw new Error("usage: node scripts/build-bank-v2.mjs <outil-entrainement-escalade.html>");
const html = readFileSync(file, "utf8");

const between = (a, b) => {
  const i = html.indexOf(a), j = html.indexOf(b, i);
  if (i < 0 || j < 0) throw new Error(`markers not found: ${a} … ${b}`);
  return html.slice(i, j);
};
const tool = new Function(
  between("const LEVELS = [", "const PERIOD_LABEL") +
  between("const DATA = [", "const PAIN_GUIDE") +
  between("const POSE_MAP = ", "\n") +
  ";return { DATA, DISCIPLINES, ENERGY, EQUIPMENT_LABELS, POSE_MAP };")();

const bankSrc = readFileSync(new URL("../src/domain/exercises.js", import.meta.url), "utf8");
const bank = new Function(
  bankSrc.slice(bankSrc.indexOf("const EX_CATS"), bankSrc.indexOf("/* La bibliothèque affichée")) +
  "return { _X, REPLACED };")();

const LANGS = ["fr", "en", "es"];
const lit = (v) => "'" + String(v).replace(/'/g, "''") + "'";
const json = (v) => lit(JSON.stringify(v)) + "::jsonb";
const level = (n) => (n <= 0 ? "all" : n <= 2 ? "inter" : "adv");
const label = (dict, key, lang) => (dict[key] && (dict[key][lang] || dict[key].fr)) || key;

const rows = tool.DATA.map((x) => {
  const title = {}, content = {};
  for (const lang of LANGS) {
    const pick = (o) => (o && (o[lang] ?? o.fr)) ?? "";
    title[lang] = pick(x.name);
    content[lang] = {
      description: pick(x.goal),
      subcategory: pick(x.subcategory),
      muscles: (pick(x.muscles) || []).join(", "),
      cues: pick(x.technique),
      dose: pick(x.protocol),
      contraindications: pick(x.precautions),
      equipment: x.equipment.map((k) => label(tool.EQUIPMENT_LABELS, k, lang)),
      disciplines: x.disciplines.map((k) => label(tool.DISCIPLINES, k, lang)),
      energy: x.energy.map((k) => label(tool.ENERGY, k, lang)),
      variants: x.variants.map((v) => ({ name: pick(v.name), desc: pick(v.desc) })),
    };
  }
  content.meta = {
    minLevel: x.minLevel, difficulty: x.difficulty, mastery: x.mastery, duration: x.duration,
    period: x.period, publics: x.publics, ageGroups: x.ageGroups,
    equipment: x.equipment, disciplines: x.disciplines, energy: x.energy,
    pose: tool.POSE_MAP[x.id] || null,
  };
  return "  (" + [lit(x.id), "'library'", lit(x.category), lit(level(x.minLevel)), json(title), json(content)].join(", ") + ")";
});

const kept = bank._X.filter((x) => !bank.REPLACED[x.id]);
const sql =
  "-- Generated by scripts/build-bank-v2.mjs from outil-entrainement-escalade.html. Do not edit by hand.\n" +
  `-- Exercise bank v2: ${tool.DATA.length} exercises with 3 variants each, 12 categories, FR/EN/ES, pose data.\n\n` +
  "-- 1. Built-in exercises that v2 replaces (assignments to them cascade).\n" +
  "delete from public.exercises where slug in (\n  " +
  Object.keys(bank.REPLACED).map(lit).join(", ") + "\n);\n\n" +
  "-- 2. Remaining built-in exercises move to the v2 categories.\n" +
  "update public.exercises e set category = v.category\nfrom (values\n" +
  kept.map((x) => `  (${lit(x.id)}, ${lit(x.cat)})`).join(",\n") +
  "\n) as v(slug, category)\nwhere e.slug = v.slug;\n\n" +
  "-- 3. v2 exercises. Re-running updates them in place.\n" +
  "insert into public.exercises (slug, visibility, category, level, title, content) values\n" +
  rows.join(",\n") +
  "\non conflict (slug) do update set\n" +
  "  category = excluded.category, level = excluded.level,\n" +
  "  title = excluded.title, content = excluded.content;\n";

const out = new URL("../supabase/migrations/20260927000100_exercise_bank_v2.sql", import.meta.url);
writeFileSync(out, sql);
console.log(`wrote ${tool.DATA.length} v2 exercises, ${Object.keys(bank.REPLACED).length} removals, ${kept.length} recategorised`);
