// Extracts the built-in exercise bank from src/domain/exercises.js into supabase/seed.sql.
// Usage: node scripts/build-seed.mjs
import { readFileSync, writeFileSync } from "node:fs";

const src = readFileSync(new URL("../src/domain/exercises.js", import.meta.url), "utf8");
const start = src.indexOf("const EX_CATS");
const end = src.indexOf("const EXERCISES = _X;");
if (start < 0 || end < 0) throw new Error("exercise bank markers not found in src/domain/exercises.js");

const exercises = new Function(src.slice(start, end) + "return _X;")();

const split = (s) => {
  const [fr, en] = String(s ?? "").split("|");
  return { fr: fr ?? "", en: en ?? fr ?? "" };
};
const lit = (v) => "'" + String(v).replace(/'/g, "''") + "'";

const rows = exercises.map((x) => {
  const f = { description: x.d, muscles: x.m, cues: x.c, errors: x.e, dose: x.dose, contraindications: x.contra };
  const content = { fr: {}, en: {} };
  for (const [k, v] of Object.entries(f)) {
    const s = split(v);
    content.fr[k] = s.fr;
    content.en[k] = s.en;
  }
  return "  (" + [lit(x.id), "'library'", lit(x.cat), lit(x.lv), lit(JSON.stringify(split(x.n))) + "::jsonb", lit(JSON.stringify(content)) + "::jsonb"].join(", ") + ")";
});

const sql =
  "-- Generated by scripts/build-seed.mjs from src/domain/exercises.js. Do not edit by hand.\n" +
  "insert into public.exercises (slug, visibility, category, level, title, content) values\n" +
  rows.join(",\n") +
  "\non conflict (slug) do nothing;\n";

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), sql);
console.log(`wrote ${exercises.length} exercises to supabase/seed.sql`);
